Часть главной страницы
velykov/airbnb-demo-frontend pull request #1
Opened 2017-11-09 08:49 UTC by velykov

Initial commit + app @evgenyrodionov

2017-11-09 14:49 UTC, evgenyrodionov commented
Коммиты на английском

2017-11-09 14:50 UTC, evgenyrodionov commented
Настрой гитконфиг

2017-11-09 14:51 UTC, evgenyrodionov commented
Зачем ты нахуярил коммиты во время моей проверки? я говорил про это

2017-11-09 14:51 UTC, evgenyrodionov commented
Коммиты говно, не описывают сделанную работу, а просто перечисление файлов. Я и так могу посмотреть, что за файлы, если зайду внутрь!

2017-11-10 13:14 UTC, evgenyrodionov commented
Другое дело

2017-11-10 13:19 UTC, imevro requested changes

2017-11-10 13:19 UTC, evgenyrodionov commented on package.json
> +    "normalize.css": "^7.0.0",
зачем ты это всё в дев накидал?

2017-11-10 13:19 UTC, evgenyrodionov commented on package.json
> +    "global": "^4.3.2",
это что?

2017-11-10 13:19 UTC, evgenyrodionov commented on package.json
> +    "create-react-app": "^1.4.3",
это зачем тут?

2017-11-10 13:19 UTC, evgenyrodionov commented on src/Destinations/cardComponent.js
> +import React from "react";
Почему файл называется в camelCase и постфикс Component у него? Перечитай второй урок — если файл называется в PascalCase, то это явный реакт-компонент

2017-11-10 13:19 UTC, evgenyrodionov commented on src/Destinations/index.js
> +        <NextLink top={109} />
фикс значение плохо тем, что развалится сразу же, как только у тебя будет другая высота

2017-11-10 13:19 UTC, evgenyrodionov commented on src/Experiences/index.js
> +            price="29"
числа передаются числом через price={29}, не строкой

2017-11-10 13:19 UTC, evgenyrodionov commented on src/Footer/index.js
> +const ListItem = styled.li`
зачем тут списки? списки для списков в тексте

2017-11-10 13:19 UTC, evgenyrodionov commented on src/Footer/index.js
> +const ListTitle = styled.div`
тайтл дивом? мощь

2017-11-10 13:19 UTC, evgenyrodionov commented on src/Footer/index.js
> +  -moz-appearance: none;
1) без вендорных префиксов — в СК есть автопрефиксер
2) не заработает в ие11

2017-11-10 13:19 UTC, evgenyrodionov commented on src/Header/index.js
> +const Offset = styled(Column)``;
оффсет делается через марджин-лефт

2017-11-10 13:19 UTC, evgenyrodionov commented on src/Reservations/cardComponent.js
> +const Label = styled.div`
очень много дивов у тебя, изучи другие теги

2017-11-10 13:19 UTC, evgenyrodionov commented on src/commons/styled.js
> +  Container,
ты мог писать export const Container

2017-11-10 14:12 UTC, velykov commented on src/Destinations/index.js
> +        <NextLink top={109} />
Какой подход лучше использовать?

2017-11-11 19:25 UTC, imevro requested changes

2017-11-11 19:25 UTC, evgenyrodionov commented on package.json
>      "normalize": "^0.3.1",
а это зачем

2017-11-11 19:25 UTC, evgenyrodionov commented on src/App.js
> +  max-width: 966px;
поч тут?

2017-11-11 19:25 UTC, evgenyrodionov commented on src/Destinations/index.js
> +          <Col xs>
а зачем тут колонки?

2017-11-11 19:25 UTC, evgenyrodionov commented on src/Footer/index.js
> +const FooterTitle = styled.b`
ты и так в футере, зачем префикс футер?

2017-11-11 19:25 UTC, evgenyrodionov commented on src/Footer/index.js
> +  -moz-appearance: none;
??

2017-11-11 19:25 UTC, evgenyrodionov commented on src/Footer/index.js
> +}
что у тебя тут произошло с отступами

2017-11-11 19:25 UTC, evgenyrodionov commented on src/Footer/index.js
> +const FooterLinks = styled(Col)`
не смешивай свои стили и стили сетки

2017-11-11 19:25 UTC, evgenyrodionov commented on src/Footer/index.js
> +              <ListItem>
ul / li только для списков в тексте, не для разметки

2017-11-11 19:25 UTC, evgenyrodionov commented on src/Reservations/Card.js
> +const Description = styled.div`
почему не параграф?

2017-11-11 19:25 UTC, evgenyrodionov commented on src/commons/seeAllLink.js
>  export default function() {
а зачем тебе эта прокладка? экспорти сразу СК

2017-11-12 03:18 UTC, velykov commented on src/Footer/index.js
> +const ListItem = styled.li`
Поправил

2017-11-12 03:27 UTC, velykov commented on package.json
>      "normalize": "^0.3.1",
Убрал лишние зависимости, а нормалайз я использую

2017-11-12 03:33 UTC, velykov commented on src/App.js
> +  max-width: 966px;
По десктопному макету ширина для секций например 966px, написал в чат с примером

2017-11-12 03:35 UTC, velykov commented on src/Destinations/index.js
> +          <Col xs>
поправил

2017-11-12 04:14 UTC, velykov commented on src/Footer/index.js
> +const FooterTitle = styled.b`
поправил

2017-11-12 04:19 UTC, velykov commented on src/Footer/index.js
> +}
поправил

2017-11-12 05:32 UTC, velykov commented on src/Footer/index.js
> +const FooterLinks = styled(Col)`
поправил

2017-11-12 05:32 UTC, velykov commented on src/Footer/index.js
> +              <ListItem>
Поправил

2017-11-12 05:33 UTC, velykov commented on src/Reservations/Card.js
> +const Description = styled.div`
Согласен, поправил на параграф

2017-11-12 05:40 UTC, velykov commented on src/commons/seeAllLink.js
>  export default function() {
Не уловил, в styled.js перенести?

2017-11-13 11:14 UTC, merged

2017-11-13 11:14 UTC, evgenyrodionov commented
Сделай пулл в мастере