Сверстал адаптивный макет + поправил футер
velykov/airbnb-demo-frontend pull request #2
Opened 2017-11-11 13:28 UTC by velykov

2017-11-11 20:28 UTC, evgenyrodionov commented
ПР в тот бранч от которого отбранчевался

2017-11-12 13:14 UTC, imevro requested changes

2017-11-12 13:14 UTC, evgenyrodionov commented on src/Footer/index.js
> +    margin-right: -12px;
что это за костыли?

2017-11-12 13:14 UTC, evgenyrodionov commented on src/Footer/index.js
> +              <FooterLink href="#">Careers</FooterLink>
ты и так в футере, зачем тебе префиксовать?

2017-11-12 13:14 UTC, evgenyrodionov commented on src/Footer/index.js
> +          <Col xs={2} md={2} mdOffset={1} lg={2} start="xs">
наследуется значение снизу — если ты определил xs={2}, то нет нужды писать md={2} и lg={2}

2017-11-13 07:36 UTC, velykov commented on src/Footer/index.js
> +    margin-right: -12px;
Поправил

2017-11-13 07:39 UTC, velykov commented on src/Footer/index.js
> +              <FooterLink href="#">Careers</FooterLink>
Из-за расширения стандартной ссылки

2017-11-13 07:41 UTC, velykov commented on src/Footer/index.js
> +              <FooterLink href="#">Careers</FooterLink>
поправил

2017-11-13 07:41 UTC, velykov commented on src/Footer/index.js
> +          <Col xs={2} md={2} mdOffset={1} lg={2} start="xs">
поправил

2017-11-13 11:13 UTC, merged